   package aplikasiRestoran.kelompok6.apps.view;

import aplikasiRestoran.kelompok6.apps.controller.PelangganController;
import aplikasiRestoran.kelompok6.apps.database.AplikasiRestoranDB;
import aplikasiRestoran.kelompok6.apps.entity.Pelanggan;
import aplikasiRestoran.kelompok6.apps.event.PelangganListener;
import aplikasiRestoran.kelompok6.apps.exception.PelangganException;
import aplikasiRestoran.kelompok6.apps.model.PelangganModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class PelangganView extends javax.swing.JFrame implements PelangganListener {

    private PelangganModel model;
    private PelangganController controller;
    
    
    public PelangganView() throws PelangganException, SQLException {
        model = new PelangganModel();
        model.setListener(this);
        
        controller = new PelangganController();
        controller.setModel(model);
        
        initComponents();
        
//        controller.tampilCmbMakanan(this);
        tampilCmbMakanan();
        tampilCmbMinuman();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    
    public javax.swing.JComboBox<String> getCmbMakanan() {
        return cmbMakanan;
    }
    public javax.swing.JComboBox<String> getCmbMinuman() {
        return cmbMinuman;
    }
    public javax.swing.JTextField getTxtHargaMakanan() {
        return txtHargaMakanan;
    }
    public javax.swing.JTextField getTxtHargaMinuman() {
        return txtHargaMinuman;
    }
    public javax.swing.JTextField getTxtNamaPemesan() {
        return txtNamaPemesan;
    }
    public javax.swing.JTextField getTxtQtyMakanan() {
        return txtQtyMakanan;
    }
    public javax.swing.JTextField getTxtQtyMinuman() {
        return txtQtyMinuman;
    }
    public javax.swing.JTextField getTxtTotalHarga() {
        return txtTotalHarga;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBody = new javax.swing.JPanel();
        panelBestSeller = new javax.swing.JPanel();
        iconJempol = new javax.swing.JLabel();
        iconTakoyaki = new javax.swing.JLabel();
        iconMieAyam = new javax.swing.JLabel();
        iconRoti = new javax.swing.JLabel();
        lblTakoyaki = new javax.swing.JLabel();
        lblMieAyam = new javax.swing.JLabel();
        lblRoti = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblMenuPilihan = new javax.swing.JLabel();
        panelPesan = new javax.swing.JPanel();
        lblMinuman = new javax.swing.JLabel();
        lblMakanan = new javax.swing.JLabel();
        cmbMakanan = new javax.swing.JComboBox<>();
        cmbMinuman = new javax.swing.JComboBox<>();
        txtHargaMinuman = new javax.swing.JTextField();
        txtHargaMakanan = new javax.swing.JTextField();
        txtQtyMinuman = new javax.swing.JTextField();
        txtQtyMakanan = new javax.swing.JTextField();
        lblQtyMakanan = new javax.swing.JLabel();
        lblHargaMakanan = new javax.swing.JLabel();
        lblHargaMinuman = new javax.swing.JLabel();
        lblQtyMinuman = new javax.swing.JLabel();
        lblTotalBayar = new javax.swing.JLabel();
        lblNamaPemesan = new javax.swing.JLabel();
        txtNamaPemesan = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnPesan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PELANGGAN");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelBody.setBackground(new java.awt.Color(192, 57, 43));
        panelBody.setMinimumSize(new java.awt.Dimension(800, 650));
        panelBody.setPreferredSize(new java.awt.Dimension(800, 690));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBestSeller.setBackground(new java.awt.Color(192, 57, 43));
        panelBestSeller.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BEST SELLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 255, 102))); // NOI18N
        panelBestSeller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconJempol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasiRestoran/kelompok6/apps/asset/jempol.png"))); // NOI18N
        panelBestSeller.add(iconJempol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, 50));

        iconTakoyaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasiRestoran/kelompok6/apps/asset/takoyaki.png"))); // NOI18N
        panelBestSeller.add(iconTakoyaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        iconMieAyam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasiRestoran/kelompok6/apps/asset/mieayam.png"))); // NOI18N
        panelBestSeller.add(iconMieAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        iconRoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasiRestoran/kelompok6/apps/asset/roti.png"))); // NOI18N
        panelBestSeller.add(iconRoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 130, -1));

        lblTakoyaki.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTakoyaki.setForeground(new java.awt.Color(255, 255, 255));
        lblTakoyaki.setText("TAKOYAKI");
        panelBestSeller.add(lblTakoyaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, -1));

        lblMieAyam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMieAyam.setForeground(new java.awt.Color(255, 255, 255));
        lblMieAyam.setText("MIE AYAM");
        panelBestSeller.add(lblMieAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));

        lblRoti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRoti.setForeground(new java.awt.Color(255, 255, 255));
        lblRoti.setText("ROTI BAKAR");
        panelBestSeller.add(lblRoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, -1));

        panelBody.add(panelBestSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 720, 260));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 102));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 320, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 102));
        panelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 320, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 102));
        panelBody.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 830, 10));

        lblMenuPilihan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMenuPilihan.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPilihan.setText("MENU PILIHAN");
        lblMenuPilihan.setMaximumSize(new java.awt.Dimension(183, 32));
        lblMenuPilihan.setMinimumSize(new java.awt.Dimension(183, 32));
        lblMenuPilihan.setPreferredSize(new java.awt.Dimension(183, 32));
        panelBody.add(lblMenuPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        panelPesan.setBackground(new java.awt.Color(192, 57, 43));
        panelPesan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panelPesan.setMinimumSize(new java.awt.Dimension(600, 180));
        panelPesan.setPreferredSize(new java.awt.Dimension(600, 180));
        panelPesan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinuman.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMinuman.setForeground(new java.awt.Color(255, 255, 102));
        lblMinuman.setText("Minuman");
        lblMinuman.setMaximumSize(new java.awt.Dimension(124, 32));
        lblMinuman.setMinimumSize(new java.awt.Dimension(124, 32));
        lblMinuman.setPreferredSize(new java.awt.Dimension(124, 32));
        panelPesan.add(lblMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        lblMakanan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMakanan.setForeground(new java.awt.Color(255, 255, 102));
        lblMakanan.setText("Makanan");
        lblMakanan.setMaximumSize(new java.awt.Dimension(119, 32));
        lblMakanan.setMinimumSize(new java.awt.Dimension(119, 32));
        lblMakanan.setPreferredSize(new java.awt.Dimension(119, 32));
        panelPesan.add(lblMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        cmbMakanan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "      -- PILIH MAKANAN --" }));
        cmbMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMakananActionPerformed(evt);
            }
        });
        panelPesan.add(cmbMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 40));

        cmbMinuman.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "      -- PILIH MINUMAN --" }));
        cmbMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinumanActionPerformed(evt);
            }
        });
        panelPesan.add(cmbMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 170, 40));

        txtHargaMinuman.setEditable(false);
        txtHargaMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHargaMinuman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelPesan.add(txtHargaMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 120, 30));

        txtHargaMakanan.setEditable(false);
        txtHargaMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHargaMakanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelPesan.add(txtHargaMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 30));

        txtQtyMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQtyMinuman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtyMinuman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyMinumanKeyReleased(evt);
            }
        });
        panelPesan.add(txtQtyMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 30, 30));

        txtQtyMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQtyMakanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtyMakanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyMakananKeyReleased(evt);
            }
        });
        panelPesan.add(txtQtyMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 30));

        lblQtyMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQtyMakanan.setForeground(new java.awt.Color(255, 255, 255));
        lblQtyMakanan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtyMakanan.setText("Jumlah  :");
        panelPesan.add(lblQtyMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblHargaMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHargaMakanan.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaMakanan.setText("Harga :");
        panelPesan.add(lblHargaMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblHargaMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHargaMinuman.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaMinuman.setText("Harga :");
        panelPesan.add(lblHargaMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        lblQtyMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQtyMinuman.setForeground(new java.awt.Color(255, 255, 255));
        lblQtyMinuman.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtyMinuman.setText("Jumlah  :");
        panelPesan.add(lblQtyMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        panelBody.add(panelPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 680, 210));

        lblTotalBayar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalBayar.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalBayar.setText("Total Bayar :");
        panelBody.add(lblTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        lblNamaPemesan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaPemesan.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaPemesan.setText("Nama Pemesan :");
        panelBody.add(lblNamaPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        txtNamaPemesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNamaPemesan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelBody.add(txtNamaPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 30));

        txtTotalHarga.setEditable(false);
        txtTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelBody.add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 30));

        btnPesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesanMouseClicked(evt);
            }
        });
        panelBody.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 110, 50));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        panelBody.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 110, 50));

        getContentPane().add(panelBody, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        controller.resetPesanan(this);
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseClicked
        try {
            controller.kirimPesanan(this);
        } catch (SQLException ex) {
            Logger.getLogger(PelangganView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PelangganException ex) {
            Logger.getLogger(PelangganView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesanMouseClicked

    int _makanan;
    int _minuman;
    
    private void cmbMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMakananActionPerformed
        String input = getCmbMakanan().getSelectedItem().toString();
        
        try {
            Connection con = new AplikasiRestoranDB().getConnection();
            String sql = "SELECT * FROM makanan WHERE nama_makanan =?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, input);
            
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
               _makanan = Integer.parseInt(rs.getString("id_makanan"));
                this.getTxtHargaMakanan().setText(rs.getString("harga_makanan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmbMakananActionPerformed

    private void cmbMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinumanActionPerformed
        String input = getCmbMinuman().getSelectedItem().toString();
        
        try {
            Connection con = new AplikasiRestoranDB().getConnection();
            String sql = "SELECT * FROM minuman WHERE nama_minuman =?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, input);
            
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
               _minuman = Integer.parseInt(rs.getString("id_minuman"));
                this.getTxtHargaMinuman().setText(rs.getString("harga_minuman"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmbMinumanActionPerformed

    private void txtQtyMinumanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyMinumanKeyReleased
        int hargaMakanan = 0;
        int hargaMinuman = 0;
        int jumlahMakanan = 0;
        int jumlahMinuman = 0;
        int total;
        try{
            hargaMakanan  = Integer.valueOf(this.getTxtHargaMakanan().getText());
            hargaMinuman  = Integer.valueOf(this.getTxtHargaMinuman().getText());
            jumlahMakanan = Integer.valueOf(this.getTxtQtyMakanan().getText());
            jumlahMinuman = Integer.valueOf(this.getTxtQtyMinuman().getText());
        
            total = (hargaMakanan * jumlahMakanan) + (hargaMinuman * jumlahMinuman);
            txtTotalHarga.setText(String.valueOf(total));
        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txtQtyMinumanKeyReleased

    private void txtQtyMakananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyMakananKeyReleased
        int hargaMakanan = 0;
        int hargaMinuman = 0;
        int jumlahMakanan = 0;
        int jumlahMinuman = 0;
        int total;
        
        try{
            hargaMakanan  = Integer.valueOf(this.getTxtHargaMakanan().getText());
            hargaMinuman  = Integer.valueOf(this.getTxtHargaMinuman().getText());
            jumlahMakanan = Integer.valueOf(this.getTxtQtyMakanan().getText());
            jumlahMinuman = Integer.valueOf(this.getTxtQtyMinuman().getText());
        
            total = (hargaMakanan * jumlahMakanan) + (hargaMinuman * jumlahMinuman);
            txtTotalHarga.setText(String.valueOf(total));
        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txtQtyMakananKeyReleased

    
    public void tampilCmbMakanan(){
        try {
            Connection con = new AplikasiRestoranDB().getConnection();
            String sql = "SELECT * FROM makanan ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                getCmbMakanan().addItem(rs.getString("nama_makanan"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }
        
    public void tampilCmbMinuman(){
        try {
            Connection con = new AplikasiRestoranDB().getConnection();
            String sql = "SELECT * FROM minuman ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                getCmbMinuman().addItem(rs.getString("nama_minuman"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PelangganView().setVisible(true);
                } catch (PelangganException ex) {
                    Logger.getLogger(PelangganView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(PelangganView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbMakanan;
    private javax.swing.JComboBox<String> cmbMinuman;
    private javax.swing.JLabel iconJempol;
    private javax.swing.JLabel iconMieAyam;
    private javax.swing.JLabel iconRoti;
    private javax.swing.JLabel iconTakoyaki;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHargaMakanan;
    private javax.swing.JLabel lblHargaMinuman;
    private javax.swing.JLabel lblMakanan;
    private javax.swing.JLabel lblMenuPilihan;
    private javax.swing.JLabel lblMieAyam;
    private javax.swing.JLabel lblMinuman;
    private javax.swing.JLabel lblNamaPemesan;
    private javax.swing.JLabel lblQtyMakanan;
    private javax.swing.JLabel lblQtyMinuman;
    private javax.swing.JLabel lblRoti;
    private javax.swing.JLabel lblTakoyaki;
    private javax.swing.JLabel lblTotalBayar;
    private javax.swing.JPanel panelBestSeller;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelPesan;
    private javax.swing.JTextField txtHargaMakanan;
    private javax.swing.JTextField txtHargaMinuman;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtQtyMakanan;
    private javax.swing.JTextField txtQtyMinuman;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PelangganModel pelanggan) {
        
        this.getCmbMakanan().setSelectedItem(model.getNamaMakanan());
        this.getCmbMinuman().setSelectedItem(model.getNamaMinuman());
        this.getTxtQtyMakanan().setText(String.valueOf(model.getQtyMakanan()));
        this.getTxtQtyMinuman().setText(String.valueOf(model.getQtyMinuman()));
        this.getTxtHargaMakanan().setText(String.valueOf(model.getHargaMakanan()));
        this.getTxtHargaMinuman().setText(String.valueOf(model.getHargaMinuman()));
        this.getTxtNamaPemesan().setText(model.getNamaPemesan());
        this.getTxtTotalHarga().setText(String.valueOf(model.getTotalHarga()));
        
    }

}
